"""Forecasting models for the research package."""

from research.models.markov import (
    classify_regime,
    classify_regime_series,
    estimate_transition_matrix,
    detect_structural_break,
    compute_markov_forecast,
)
from research.models.ensemble import (
    MarketInput,
    OtherSignals,
    EnsembleResult,
    adjust_yes_bias,
    compute_market_quality,
    compute_conditional_return,
    compute_polymarket_signal,
    compute_ensemble,
    compute_variance,
    compute_ci,
    compute_quality_score,
    score_to_grade,
    run_ensemble,
)
from research.models.trajectory import (
    RegimeStats,
    TrajectoryPoint,
    compute_trajectory,
    compute_horizon_drift_vol,
    compute_scenario_probabilities,
    normal_cdf,
    student_t_cdf,
    student_t_ppf,
    student_t_survival,
    log_normal_survival,
    interpolate_survival,
)

__all__ = [
    "classify_regime",
    "classify_regime_series",
    "estimate_transition_matrix",
    "detect_structural_break",
    "compute_markov_forecast",
    "MarketInput",
    "OtherSignals",
    "EnsembleResult",
    "adjust_yes_bias",
    "compute_market_quality",
    "compute_conditional_return",
    "compute_polymarket_signal",
    "compute_ensemble",
    "compute_variance",
    "compute_ci",
    "compute_quality_score",
    "score_to_grade",
    "run_ensemble",
    "RegimeStats",
    "TrajectoryPoint",
    "compute_trajectory",
    "compute_horizon_drift_vol",
    "compute_scenario_probabilities",
    "normal_cdf",
    "student_t_cdf",
    "student_t_ppf",
    "student_t_survival",
    "log_normal_survival",
    "interpolate_survival",
]
